---
- name: Check webserver for correct response
  uri:
    url: "http://frontend1.06e0.example.opentlc.com/ping"
    return_content: yes
  until: '"alive" in result.content'
  retries: 10
  delay: 1
  register: result
  delegate_to: localhost